defmodule Mix.Tasks.Migration do
  use Mix.Task

  def run(migration_name) do
    time =
      DateTime.utc_now()
      |> Calendar.strftime("%Y%m%d%H%M%S")

    file_name = Enum.join([time, migration_name], "_") <> ".exs"

    file_content =
      migration_name
      |> Enum.at(0)
      |> String.split("_")
      |> Enum.map(&String.capitalize/1)
      |> Enum.join("")
      |> contents

    File.write("priv/repo/migrations/#{file_name}", file_content)
  end

  def contents(class_name) do
    ~s"""
    defmodule Budgetalx.Repo.Migrations.#{class_name} do
      use Ecto.Migration
      import Budgetalx.Migration

      def up do
        execute_sql(\"\"\"
          create table example (
            id bigint generated by default as identity primary key,
            inserted_at timestamptz not null default now(),
            updated_at timestamptz not null default now()
          );
        \"\"\")
      end

      def down do
        execute_sql(\"\"\"
          drop table example;
        \"\"\")
      end
    end
    """
  end
end
